import { openCoreStore } from "../../core/src/index.ts";
import { DaemonCore } from "../src/loops.ts";
import type { ReconnectToolsReceipt } from "../../core/src/reconnectTools.ts";
import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { FakeDriver, makeDaemonDir, startDaemon, waitFor } from "./helpers.ts";
import { runV2Cli } from "../../cli/src/main.ts";
import type { ReconnectToolsResult, SpawnResult, ViewResult, MailboxResult, SendRpcResult } from "../src/protocol.ts";

const fakeCodex = new URL("../../driver-hsr/test-agent/fake-codex.mjs", import.meta.url).pathname;

test("reconnect RPC/CLI: active-turn acceptance, send race, daemon adoption and authoritative receipt", { timeout: 120_000 }, async t => {
  const root = mkdtempSync(join(tmpdir(), "hb-reconnect-rpc-"));
  const home = join(root, "native"); mkdirSync(home);
  const log = join(root, "rpc.jsonl");
  const gateways = join(root, "gateways"); mkdirSync(gateways);
  writeFileSync(join(gateways, "apiary.json"), JSON.stringify({ name: "apiary", protocol: "mcp", gatewayRev: 1, startedAt: new Date().toISOString(), stateless: true, shim: { command: process.execPath, args: ["fixture.mjs"] }, env: {} }));
  const rig = makeDaemonDir({ agents: { codex: { command: process.execPath, args: [fakeCodex], adapter: "codex", env: { CODEX_HOME: home, FAKE_CODEX_RPC_LOG: log } } } });
  const env = { HIVE_STORE_ROOT: root, HIVE_GATEWAYS_DISABLE: "0" };
  let daemon = await startDaemon(rig.dir, { env });
  let client = await daemon.client();
  t.after(async () => { client.close(); await daemon.stop(); rig.cleanup(); rmSync(root, { recursive: true, force: true }); });
  const bee = await client.request<SpawnResult>("spawn", { name: "owner", agent: "codex", cwd: root });
  const original = await waitFor(async () => {
    const view = await client.request<ViewResult>("view", { beeId: bee.beeId });
    return view.runtime?.state === "idle" && view.bee?.providerSessionId ? view : null;
  }, "native session idle", 60_000);
  await client.request("send", { beeId: bee.beeId, body: "@slow:30000" });
  await waitFor(async () => (await client.request<ViewResult>("view", { beeId: bee.beeId })).runtime?.state === "running", "active turn");
  const request = { beeId: bee.beeId, idempotencyKey: "reconnect-once" };
  const accepted = await client.request<ReconnectToolsResult>("bee.reconnectTools", request);
  assert.equal(accepted.state, "queued");
  assert.equal(accepted.receipt, null);
  const steer = await client.request<SendRpcResult>("send", { beeId: bee.beeId, body: "still steerable", urgency: "next" });
  await waitFor(async () => (await client.request<MailboxResult>("mailbox", { beeId: bee.beeId })).messages.some(m => m.id === steer.messageId && m.deliveredAt !== null), "mid-turn send remains accepted");
  assert.equal((await client.request<ReconnectToolsResult>("bee.reconnectTools", request)).commandId, accepted.commandId);
  await assert.rejects(client.request("send", { beeId: bee.beeId, body: "wrong key", idempotencyKey: request.idempotencyKey }), { code: "idempotency_conflict" });
  await daemon.kill(); client.close();
  daemon = await startDaemon(rig.dir, { env }); client = await daemon.client();
  const afterAdoption = await client.request<ViewResult>("view", { beeId: bee.beeId });
  assert.equal(afterAdoption.runtime?.pid, original.runtime?.pid);
  assert.equal(afterAdoption.runtime?.generation, original.runtime?.generation);
  await client.request("bee.interrupt", { beeId: bee.beeId });
  const result = await waitFor(async () => {
    const row = await client.request<ReconnectToolsResult>("bee.reconnectTools.get", { beeId: bee.beeId, commandId: accepted.commandId });
    return row.state === "done" || row.state === "failed" ? row : null;
  }, "reconnect receipt", 60_000);
  assert.equal(result.state, "done", JSON.stringify(result));
  assert.equal(result.receipt?.modelTools, "refresh_pending_next_turn");
  assert.deepEqual(result.receipt?.targets, ["apiary"]);
  assert.equal(result.receipt?.threadId, original.bee?.providerSessionId);
  const after = await client.request<ViewResult>("view", { beeId: bee.beeId });
  assert.equal(after.runtime?.pid, original.runtime?.pid);
  assert.equal(after.runtime?.generation, original.runtime?.generation);
  const duplicate = await client.request<ReconnectToolsResult>("bee.reconnectTools", request);
  assert.deepEqual(duplicate, result);
  const stdout: string[] = [];
  assert.equal(await runV2Cli(["reconnect-tools", bee.beeId, "--command-id", String(result.commandId), "--data-dir", rig.dir, "--json"], { out: text => stdout.push(text), err: text => assert.fail(text) }), 0);
  assert.deepEqual(JSON.parse(stdout.at(-1)!), result);
  const calls = readFileSync(log, "utf8").trim().split("\n").map(line => JSON.parse(line));
  assert.equal(calls.filter(c => c.method === "config/mcpServer/reload").length, 1);
  assert.equal(calls.filter(c => c.method === "thread/start").length, 1);
  assert.equal(calls.filter(c => c.method === "thread/resume").length, 0);
  const unsupported = await client.request<SpawnResult>("spawn", { name: "unsupported", agent: "stub", cwd: root });
  await assert.rejects(client.request("bee.reconnectTools", { beeId: unsupported.beeId }), { code: "reconnect_unsupported" });
  await assert.rejects(client.request("bee.reconnectTools.get", { beeId: unsupported.beeId, commandId: result.commandId }), { code: "reconnect_not_found" });
  await assert.rejects(client.request("bee.reconnectTools", { beeId: bee.beeId, method: "anything" }), { code: "invalid_request" });
});


test("idle policy cannot stop reconnect work; racing mail waits durably for completion", async t => {
  const dir = mkdtempSync(join(tmpdir(), "hb-reconnect-loop-"));
  let now = 1000;
  const store = openCoreStore(join(dir, "store.sqlite3"), { now: () => now });
  const driver = new FakeDriver(() => now);
  let complete!: (receipt: ReconnectToolsReceipt) => void;
  const effect = new Promise<ReconnectToolsReceipt>(resolve => { complete = resolve; });
  const core = new DaemonCore({ store, driver, now: () => now, log: () => {}, policy: { commandsPerStep: 8, bootHangTimeoutSteps: 5000, idleWindowSteps: 5 }, reconnectTools: () => effect });
  t.after(() => { core.detachReconnectOwner(); store.close(); rmSync(dir, { recursive: true, force: true }); });
  core.boot();
  const { bee } = store.createBee({ name: "owner", agent: "codex", substrate: "hsr", cwd: dir });
  store.enqueueCommand("spawn", bee.id);
  core.step(); core.step();
  assert.equal(store.currentRuntime(bee.id)?.state, "idle");
  const command = store.enqueueCommand("reconnect_tools", bee.id);
  now += 100;
  core.step();
  await new Promise<void>(resolve => setImmediate(resolve));
  assert.equal(store.getCommand(command.id)?.status, "running");
  core.step();
  assert.equal(store.currentRuntime(bee.id)?.state, "idle");
  assert.equal(store.listCommands({ beeId: bee.id }).some(c => c.verb === "stop"), false);
  const mail = store.send(bee.id, "next turn");
  core.step();
  assert.equal(store.getMessage(mail.message.id)?.deliveredAt, null);
  complete({ outcome: "reloaded", threadId: "same", targets: ["apiary"], modelTools: "refresh_pending_next_turn" });
  await new Promise<void>(resolve => setImmediate(resolve));
  assert.equal(store.getCommand(command.id)?.status, "done");
  core.step();
  assert.notEqual(store.getMessage(mail.message.id)?.deliveredAt, null);
  assert.equal(driver.starts.length, 1);
});
