import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { makeDaemonDir, startDaemon, waitFor } from "./helpers.ts";
import { runV2Cli } from "../../cli/src/main.ts";
import type { SnapshotResult, SpawnResult, ThreadOperationResult, ViewResult, SendRpcResult, MailboxResult, WatchFrame } from "../src/protocol.ts";

const native = fileURLToPath(new URL("./thread-codex.mjs", import.meta.url));
const errorCode = (code: string) => (error: unknown) => error instanceof Error && "code" in error && error.code === code;

test("thread RPC: prompt receipt, disconnect/restart, history events, native compaction gate, queued mail and owner refusals", { timeout: 90000 }, async t => {
  const root = mkdtempSync(join(tmpdir(), "hb-thread-rpc-"));
  const home = join(root, "home"); mkdirSync(home);
  const compactGate = join(root, "compact-go"); const startGate = join(root, "start-go"); const rpcLog = join(root, "rpc.jsonl");
  const rig = makeDaemonDir({ naming: { auto: false }, agents: { codex: { command: process.execPath, args: [native, "app-server"], adapter: "codex", env: { CODEX_HOME: home, THREAD_COMPACT_GATE: compactGate, THREAD_START_GATE: startGate, THREAD_RPC_LOG: rpcLog } } } });
  let daemon = await startDaemon(rig.dir); let client = await daemon.client();
  t.after(async () => { client.close(); await daemon.stop(); rig.cleanup(); rmSync(root, { recursive: true, force: true }); });
  const watcher = await daemon.client(); const frames: WatchFrame[] = [];
  watcher.onEvent = frame => frames.push(frame); t.after(() => watcher.close());
  await watcher.request("watch");
  const source = await client.request<SpawnResult>("spawn", { name: "source", agent: "codex", cwd: root });
  const original = await waitFor(async () => { const v = await client.request<ViewResult>("view", { beeId: source.beeId }); return v.bee?.providerSessionId ? v : null; }, "source session");
  const params = { beeId: source.beeId, sourceProviderSessionId: original.bee!.providerSessionId, instruction: "Preserve the migration decision", idempotencyKey: "durable-request" };
  const start = Date.now();
  const receipt = await client.request<ThreadOperationResult>("thread.handoff", params);
  assert.ok(Date.now() - start < 3000, "acceptance does not wait for closed compaction/start gates");
  assert.equal(receipt.operation.phase, "copying");
  assert.equal(receipt.operation.compacted, false);
  const successor = receipt.operation.successorBeeId;
  const cliOut: string[] = []; const cliErr: string[] = [];
  const io = { out: (line: string) => cliOut.push(line), err: (line: string) => cliErr.push(line) };
  assert.equal(await runV2Cli(["thread-handoff", source.beeId, "--instruction", params.instruction, "--idempotency-key", params.idempotencyKey, "--data-dir", rig.dir, "--json"], io), 0);
  assert.equal(JSON.parse(cliOut.pop()!).operation.successorBeeId, successor);
  assert.equal(await runV2Cli(["thread-operation", "get", receipt.operation.id, "--data-dir", rig.dir, "--json"], io), 0);
  assert.equal(JSON.parse(cliOut.pop()!).operation.id, receipt.operation.id);
  for (const args of [["--prompt", "compact"], ["--instruction", "compact"], ["compact"], ["--model", "other-provider"]]) {
    assert.equal(await runV2Cli(["thread-fork", source.beeId, ...args, "--data-dir", rig.dir], io), 1);
  }
  const later = await client.request<SendRpcResult>("send", { beeId: successor, body: "later user instruction", urgency: "now" });
  const op = () => client.request<ThreadOperationResult>("thread.operation.get", { operationId: receipt.operation.id });
  await waitFor(async () => (await op()).operation.phase === "compacting", "compacting");
  const beforeRestart = await client.request<SnapshotResult>("snapshot");
  const row = beforeRestart.threadOperations.find(o => o.id === receipt.operation.id)!;
  assert.equal(row.transcriptReady, true);
  await waitFor(() => frames.some(frame => frame.type === "delta" && frame.events.some(event => event.kind === "thread_operation.put" && (event.payload.operation as { transcriptReady: boolean }).transcriptReady)), "transcript readiness delta");
  for (const frame of frames) if (frame.type === "delta") for (const event of frame.events) if (event.kind === "thread_operation.put") assert.deepEqual(Object.keys(event.payload), ["operation"], "watch excludes private worker and source path metadata");
  const transcript = await client.request<{ data: string }>("thread.transcript", { operationId: row.id });
  assert.match(Buffer.from(transcript.data, "base64").toString(), /Original history/);
  const pending = await client.request<MailboxResult>("mailbox", { beeId: successor });
  assert.ok(pending.messages.every(m => m.deliveredAt === null));
  await client.request("send", { beeId: source.beeId, body: "SOURCE LATER OUTPUT" });
  await assert.rejects(client.request("thread.handoff", { ...params, instruction: "different" }), errorCode("idempotency_conflict"));
  await assert.rejects(client.request("thread.handoff", { ...params, sourceNode: "other-machine" }), errorCode("thread_remote_unsupported"));
  await assert.rejects(client.request("thread.fork", params), errorCode("thread_unsupported"));
  await assert.rejects(client.request("bee.fork", { beeId: source.beeId, prompt: "compact" }), errorCode("thread_unsupported"));
  await assert.rejects(client.request("bee.setArgs", { beeId: successor, args: [] }), errorCode("thread_busy"));
  await assert.rejects(client.request("bee.fork", { beeId: successor }), errorCode("thread_busy"));
  await daemon.kill(); client.close();
  daemon = await startDaemon(rig.dir); client = await daemon.client();
  const duplicate = await client.request<ThreadOperationResult>("thread.handoff", params);
  assert.equal(duplicate.deduped, true);
  assert.equal(duplicate.operation.successorBeeId, successor);
  assert.equal(duplicate.operation.id, row.id);
  const afterReload = await client.request<{ data: string }>("thread.transcript", { operationId: row.id });
  assert.equal(afterReload.data, transcript.data, "source output cannot change inherited history after reload");
  writeFileSync(compactGate, "go");
  await waitFor(async () => (await op()).operation.phase === "starting", "compacted, waiting on provider readiness", 20000);
  assert.equal((await op()).operation.compacted, true);
  assert.ok((await client.request<MailboxResult>("mailbox", { beeId: successor })).messages.every(m => m.deliveredAt === null));
  const starting = await waitFor(async () => { const v = await client.request<ViewResult>("view", { beeId: successor }); return v.runtime?.pid ? v : null; }, "starting runtime identity");
  const startingGeneration = starting.runtime?.generation;
  await daemon.kill(); client.close();
  daemon = await startDaemon(rig.dir); client = await daemon.client();
  assert.equal((await op()).operation.successorBeeId, successor);
  writeFileSync(startGate, "go");
  try { await waitFor(async () => (await op()).operation.phase === "ready", "ready", 20000); }
  catch (error) {
    t.diagnostic(JSON.stringify({ operation: await op(), view: await client.request("view", { beeId: successor }), commands: await client.request("commands", { beeId: successor }), log: daemon.output().slice(-18000) }));
    throw error;
  }
  await waitFor(async () => (await client.request<MailboxResult>("mailbox", { beeId: successor })).messages.find(m => m.id === later.messageId)?.deliveredAt != null, "later message delivered", 20000);
  const snapshot = await client.request<SnapshotResult>("snapshot");
  assert.equal((await client.request<ViewResult>("view", { beeId: successor })).runtime?.generation, startingGeneration, "starting runtime survives daemon restart");
  assert.equal(snapshot.views.filter(v => v.bee?.forkedFrom === source.beeId).length, 1);
  const originalNow = await client.request<ViewResult>("view", { beeId: source.beeId });
  assert.equal(originalNow.bee?.lifecycle, "active");
  assert.equal(originalNow.bee?.providerSessionId, original.bee!.providerSessionId);
  const calls = readFileSync(rpcLog, "utf8").trim().split("\n").map(line => JSON.parse(line));
  const compactor = calls.find(c => c.method === "thread/resume" && c.params.config?.compact_prompt);
  assert.match(compactor.params.baseInstructions, /Preserve the migration decision/);
  assert.ok(calls.some(c => c.pid === compactor.pid && c.method === "thread/compact/start"));
  assert.ok(!calls.some(c => c.pid === compactor.pid && ["turn/start", "turn/steer"].includes(c.method)), "compaction never becomes an ordinary message");
});

test("native method refusal is typed, retry keys recover one successor, and plain Fork requests no compaction", { timeout: 60000 }, async t => {
  const root = mkdtempSync(join(tmpdir(), "hb-thread-refusal-"));
  const home = join(root, "home"); const unsupported = join(root, "unsupported"); const rpcLog = join(root, "rpc.jsonl");
  writeFileSync(unsupported, "unsupported");
  const rig = makeDaemonDir({ naming: { auto: false }, agents: { codex: { command: process.execPath, args: [native, "app-server"], adapter: "codex", env: { CODEX_HOME: home, THREAD_UNSUPPORTED_FILE: unsupported, THREAD_RPC_LOG: rpcLog } } } });
  const daemon = await startDaemon(rig.dir); const client = await daemon.client();
  t.after(async () => { client.close(); await daemon.stop(); rig.cleanup(); rmSync(root, { recursive: true, force: true }); });
  const capabilities = await client.request<{ executors: Array<{ instructionCompaction: boolean }> }>("thread.capabilities");
  assert.equal(capabilities.executors[0]?.instructionCompaction, true);
  const source = await client.request<SpawnResult>("spawn", { name: "source", agent: "codex", cwd: root });
  const original = await waitFor(async () => { const v = await client.request<ViewResult>("view", { beeId: source.beeId }); return v.bee?.providerSessionId ? v : null; }, "source session");
  const identity = { beeId: source.beeId, sourceProviderSessionId: original.bee!.providerSessionId };
  const params = { ...identity, instruction: "Keep the failure diagnosis", idempotencyKey: "refused-handoff" };
  const receipt = await client.request<ThreadOperationResult>("thread.handoff", params);
  const op = () => client.request<ThreadOperationResult>("thread.operation.get", { operationId: receipt.operation.id });
  await waitFor(async () => (await op()).operation.phase === "failed", "typed native refusal");
  assert.equal((await op()).operation.failure?.code, "compaction_unsupported");
  assert.equal((await op()).operation.failure?.stage, "compacting");
  const queued = await client.request<SendRpcResult>("send", { beeId: receipt.operation.successorBeeId, body: "queued during failure" });
  assert.ok((await client.request<MailboxResult>("mailbox", { beeId: receipt.operation.successorBeeId })).messages.every(m => m.deliveredAt === null));
  assert.equal((await client.request<ThreadOperationResult>("thread.handoff", params)).operation.phase, "failed", "replay does not retry");
  rmSync(unsupported);
  const retry = { operationId: receipt.operation.id, idempotencyKey: "recover-native-method" };
  const firstRetry = await client.request<ThreadOperationResult>("thread.operation.retry", retry);
  const secondRetry = await client.request<ThreadOperationResult>("thread.operation.retry", retry);
  assert.equal(firstRetry.operation.successorBeeId, receipt.operation.successorBeeId);
  assert.deepEqual(secondRetry.operation, firstRetry.operation);
  await assert.rejects(client.request("thread.operation.retry", { ...retry, operationId: "another-operation" }), errorCode("idempotency_conflict"));
  await assert.rejects(client.request("send", { beeId: source.beeId, body: "key collision", idempotencyKey: retry.idempotencyKey }), errorCode("idempotency_conflict"));
  await waitFor(async () => (await op()).operation.phase === "ready", "retry ready");
  await waitFor(async () => (await client.request<MailboxResult>("mailbox", { beeId: receipt.operation.successorBeeId })).messages.find(m => m.id === queued.messageId)?.deliveredAt != null, "held mail released");
  const fork = await client.request<ThreadOperationResult>("thread.fork", { ...identity, idempotencyKey: "plain-copy" });
  await waitFor(async () => (await client.request<ThreadOperationResult>("thread.operation.get", { operationId: fork.operation.id })).operation.phase === "ready", "fork ready");
  assert.equal(fork.operation.continuationMessageId, null);
  assert.equal((await client.request<MailboxResult>("mailbox", { beeId: fork.operation.successorBeeId })).messages.length, 0);
  const calls = readFileSync(rpcLog, "utf8").trim().split("\n").map(line => JSON.parse(line));
  assert.ok(!calls.some(c => c.method === "thread/compact/start" && c.params.threadId === fork.operation.successorProviderSessionId));
  const preserved = await client.request<ViewResult>("view", { beeId: source.beeId });
  assert.equal(preserved.bee?.lifecycle, "active");
  assert.equal(preserved.bee?.providerSessionId, identity.sourceProviderSessionId);
});
