#!/usr/bin/env node
/**
 * perf-map — tooling for a project-local performance map generated by
 * /create-perf-skill. Copy this file into the repo (e.g. scripts/perf-map.mjs),
 * set MAP_DIR below, and describe the census in <MAP_DIR>/census.config.json.
 *
 *   node scripts/perf-map.mjs census   [--out <file>]     deterministic inventory of measurable structure
 *   node scripts/perf-map.mjs validate                    every workloads/<id>.json against record.schema.json
 *   node scripts/perf-map.mjs index                       rewrite workloads/README.md from the records
 *   node scripts/perf-map.mjs drift    [--census <file>]  census keys nobody accounts for, dead accounts,
 *                                                         owners whose content changed since a receipt
 *   node scripts/perf-map.mjs check    <receipt.json> [--tolerance 0.1]
 *                                                         verdict for a measured receipt against the record's
 *                                                         budget, invariant and baseline
 *
 * The census is deterministic: fixed sources, fixed patterns, sorted output,
 * content hashes from `git hash-object`. It proves omissions; it does not
 * judge. Agents write the workload records; `drift` says what they no longer
 * cover. Accounts and gaps may end a key in `*` to cover a prefix.
 *
 * census.config.json:
 * {
 *   "version": 1,
 *   "sourceRoots": ["src", "packages/core/src"],
 *   "extensions": "\\.(ts|tsx|mts|cts)$",
 *   "exclude": "(\\.test\\.|/test/|/vendor/|/dist/|/node_modules/)",
 *   "registries": [
 *     { "inventory": "entry-points", "prefix": "view:", "file": "packages/core/src/views.ts", "kind": "const-map", "name": "ViewTypes" },
 *     { "inventory": "boundaries", "prefix": "ipc:", "file": "src/preload/bridge.contract.json", "kind": "json-channels", "channelKey": "channel" }
 *   ],
 *   "patterns": [
 *     { "inventory": "work-triggers", "prefix": "timer:", "regex": "\\bsetInterval\\(", "mode": "ordinal" },
 *     { "inventory": "resource-owners", "prefix": "sqlite:", "regex": "\\b(?:DatabaseSync|better-sqlite3)\\b", "mode": "file" },
 *     { "inventory": "boundaries", "prefix": "verb:", "regex": "case '([a-z][a-zA-Z0-9.]*)':", "mode": "capture", "pathFilter": "domains/[^/]+/domain\\.ts$", "keyTemplate": "{seg:3}.{1}" }
 *   ]
 * }
 * mode ordinal  -> key = prefix + path + '#' + n (n-th match in the file); stable across line moves
 * mode file     -> key = prefix + path (one entry when the file matches)
 * mode capture  -> key = prefix + keyTemplate, where {1}..{9} are capture groups, {seg:N} the N-th path
 *                  segment (0-based), {path} the path; duplicates within a file collapse to one entry
 * Matches on lines starting with a comment marker are skipped; `skipIfSnippet` drops matches whose
 * line matches that regex (e.g. a method definition that happens to be named like the call).
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
export const REPO = resolve(here, '..')
/** Set this to the generated skill's workloads directory. */
export const MAP_DIR = join(REPO, '.agents/skills/perf-honeybee/workloads')
export const CENSUS_VERSION = 1

// ---------------------------------------------------------------- config

export function loadConfig(mapDir = MAP_DIR) {
  const p = join(mapDir, 'census.config.json')
  if (!existsSync(p)) throw new Error(`missing ${p}`)
  const c = JSON.parse(readFileSync(p, 'utf8'))
  return {
    version: c.version ?? 1,
    sourceRoots: c.sourceRoots ?? [],
    extensions: new RegExp(c.extensions ?? '\\.(ts|tsx|mts|cts|js|mjs|py|go|rs)$'),
    exclude: new RegExp(c.exclude ?? '(\\.test\\.|\\.spec\\.|/test/|/tests/|/__tests__/|/vendor/|/dist/|/node_modules/|/target/)'),
    registries: c.registries ?? [],
    patterns: (c.patterns ?? []).map((p) => ({ ...p, re: new RegExp(p.regex, (p.flags ?? '').replace('g', '') + 'g'), pathFilter: p.pathFilter ? new RegExp(p.pathFilter) : null, skipIfSnippet: p.skipIfSnippet ? new RegExp(p.skipIfSnippet) : null })),
  }
}

// ---------------------------------------------------------------- helpers

function walk(dir, ext, out = []) {
  if (!existsSync(dir)) return out
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name)
    const st = statSync(full)
    if (st.isDirectory()) walk(full, ext, out)
    else if (ext.test(name)) out.push(full)
  }
  return out
}

function sourceFiles(repo, cfg) {
  const files = []
  for (const root of cfg.sourceRoots) walk(join(repo, root), cfg.extensions, files)
  return files.map((f) => relative(repo, f)).filter((f) => !cfg.exclude.test('/' + f)).sort()
}

function hashObjects(repo, files) {
  if (files.length === 0) return new Map()
  const out = execFileSync('git', ['hash-object', '--stdin-paths'], { cwd: repo, input: files.join('\n') + '\n', encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 })
  const hashes = out.trim().split('\n')
  return new Map(files.map((f, i) => [f, hashes[i]]))
}

function lineOf(text, index) {
  let line = 1
  for (let i = 0; i < index; i++) if (text.charCodeAt(i) === 10) line++
  return line
}

function snippetAt(text, index) {
  const start = text.lastIndexOf('\n', index) + 1
  let end = text.indexOf('\n', index)
  if (end === -1) end = text.length
  return text.slice(start, end).trim().slice(0, 160)
}

/** Every match of `re` in `text` as {line, snippet, match}, skipping comment lines. */
function sites(text, re) {
  const found = []
  re.lastIndex = 0
  let m
  while ((m = re.exec(text))) {
    const snippet = snippetAt(text, m.index)
    if (/^(\/\/|\*|\/\*|#)/.test(snippet)) continue
    found.push({ index: m.index, line: lineOf(text, m.index), snippet, match: m })
    if (m[0].length === 0) re.lastIndex++
  }
  return found
}

function constMap(text, name) {
  const block = text.match(new RegExp(`export const ${name}\\s*=\\s*\\{([\\s\\S]*?)\\n\\}`))
  if (!block) return []
  const ids = []
  for (const m of block[1].matchAll(/^\s+[A-Za-z0-9_]+:\s*['"]([^'"]+)['"]/gm)) ids.push(m[1])
  return ids
}

function keyFrom(template, path, match, n) {
  const segs = path.split('/')
  return template
    .replace(/\{seg:(\d+)\}/g, (_, i) => segs[Number(i)] ?? '')
    .replace(/\{path\}/g, path)
    .replace(/\{n\}/g, String(n))
    .replace(/\{(\d)\}/g, (_, g) => match[Number(g)] ?? '')
}

function read(repo, path) {
  return readFileSync(join(repo, path), 'utf8')
}

function gitHead(repo) {
  try {
    return execFileSync('git', ['rev-parse', 'HEAD'], { cwd: repo, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
  } catch {
    return null
  }
}

// ---------------------------------------------------------------- census

export function census(repo = REPO, cfg = loadConfig()) {
  const files = sourceFiles(repo, cfg)
  const registryFiles = cfg.registries.map((r) => r.file).filter((f) => existsSync(join(repo, f)))
  const hashes = hashObjects(repo, [...new Set([...files, ...registryFiles])])
  const entries = []
  const add = (inventory, key, path, extra = {}) => entries.push({ key, inventory, path, blob: hashes.get(path) ?? null, ...extra })

  for (const r of cfg.registries) {
    if (!existsSync(join(repo, r.file))) continue
    const text = read(repo, r.file)
    if (r.kind === 'const-map') for (const id of constMap(text, r.name)) add(r.inventory, r.prefix + id, r.file)
    else if (r.kind === 'json-channels') {
      const json = JSON.parse(text)
      const seen = new Set()
      for (const [api, def] of Object.entries(json)) {
        const channel = def?.[r.channelKey ?? 'channel']
        if (typeof channel === 'string' && !seen.has(channel)) { seen.add(channel); add(r.inventory, r.prefix + channel, r.file, { api, kind: def.kind }) }
      }
    }
  }

  for (const path of files) {
    const text = read(repo, path)
    for (const p of cfg.patterns) {
      if (p.pathFilter && !p.pathFilter.test(path)) continue
      const found = sites(text, p.re).filter((s) => !(p.skipIfSnippet && p.skipIfSnippet.test(s.snippet)))
      if (found.length === 0) continue
      if (p.mode === 'file') { add(p.inventory, p.prefix + path, path); continue }
      if (p.mode === 'capture') {
        const keys = new Set()
        for (const s of found) keys.add(p.prefix + keyFrom(p.keyTemplate ?? '{1}', path, s.match, 0))
        for (const key of [...keys].sort()) if (!p.dedupe || !entries.some((e) => e.key === key)) add(p.inventory, key, path)
        continue
      }
      let n = 0
      for (const s of found) add(p.inventory, p.prefix + keyFrom(p.keyTemplate ?? '{path}#{n}', path, s.match, ++n), path, { line: s.line, snippet: s.snippet })
    }
  }

  entries.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0))
  const counts = {}
  for (const e of entries) counts[e.inventory] = (counts[e.inventory] ?? 0) + 1
  return { censusVersion: CENSUS_VERSION, configVersion: cfg.version, head: gitHead(repo), sourceRoots: cfg.sourceRoots, fileCount: files.length, counts, files: Object.fromEntries(files.map((f) => [f, hashes.get(f)])), entries }
}

// ---------------------------------------------------------------- records

export function loadSchema(mapDir = MAP_DIR) {
  return JSON.parse(readFileSync(join(mapDir, 'record.schema.json'), 'utf8'))
}

export function loadRecords(mapDir = MAP_DIR) {
  if (!existsSync(mapDir)) return []
  return readdirSync(mapDir)
    .filter((f) => f.endsWith('.json') && !['record.schema.json', 'gaps.json', 'census.config.json'].includes(f) && !f.startsWith('census'))
    .sort()
    .map((f) => ({ file: f, record: JSON.parse(readFileSync(join(mapDir, f), 'utf8')) }))
}

export function loadGaps(mapDir = MAP_DIR) {
  const p = join(mapDir, 'gaps.json')
  return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : { gaps: [] }
}

/** Minimal JSON-schema checker sufficient for record.schema.json. */
export function validateAgainst(schema, value, root = schema, path = '$', errors = []) {
  if (schema.$ref) {
    const ref = schema.$ref.replace('#/', '').split('/').reduce((o, k) => o?.[k], root)
    if (!ref) errors.push(`${path}: unresolved $ref ${schema.$ref}`)
    else validateAgainst(ref, value, root, path, errors)
    return errors
  }
  if ('const' in schema && value !== schema.const) errors.push(`${path}: expected ${JSON.stringify(schema.const)}`)
  if (schema.enum && !schema.enum.includes(value)) errors.push(`${path}: ${JSON.stringify(value)} not in ${JSON.stringify(schema.enum)}`)
  if (schema.type) {
    const types = Array.isArray(schema.type) ? schema.type : [schema.type]
    const actual = Array.isArray(value) ? 'array' : value === null ? 'null' : typeof value
    const ok = types.some((t) => (t === 'integer' ? Number.isInteger(value) : t === actual))
    if (!ok) { errors.push(`${path}: expected ${types.join('|')}, got ${actual}`); return errors }
  }
  if (typeof value === 'string' && schema.pattern && !new RegExp(schema.pattern).test(value)) errors.push(`${path}: does not match ${schema.pattern}`)
  if (typeof value === 'number' && schema.minimum !== undefined && value < schema.minimum) errors.push(`${path}: below minimum ${schema.minimum}`)
  if (Array.isArray(value)) {
    if (schema.minItems !== undefined && value.length < schema.minItems) errors.push(`${path}: needs at least ${schema.minItems} items`)
    if (schema.items) value.forEach((v, i) => validateAgainst(schema.items, v, root, `${path}[${i}]`, errors))
  }
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    for (const k of schema.required ?? []) if (!(k in value)) errors.push(`${path}: missing ${k}`)
    for (const [k, v] of Object.entries(value)) {
      const prop = schema.properties?.[k]
      const patterned = Object.entries(schema.patternProperties ?? {}).find(([re]) => new RegExp(re).test(k))?.[1]
      if (prop) validateAgainst(prop, v, root, `${path}.${k}`, errors)
      else if (patterned) validateAgainst(patterned, v, root, `${path}.${k}`, errors)
      else if (schema.additionalProperties === false) errors.push(`${path}: unexpected property ${k}`)
      else if (schema.additionalProperties && typeof schema.additionalProperties === 'object') validateAgainst(schema.additionalProperties, v, root, `${path}.${k}`, errors)
    }
  }
  return errors
}

export function validateRecords(mapDir = MAP_DIR) {
  const schema = loadSchema(mapDir)
  const problems = []
  const ids = new Set()
  for (const { file, record } of loadRecords(mapDir)) {
    const errors = validateAgainst(schema, record)
    if (record.id && file !== `${record.id}.json`) errors.push(`$.id: ${record.id} does not match file name ${file}`)
    if (ids.has(record.id)) errors.push(`$.id: duplicate ${record.id}`)
    ids.add(record.id)
    if (!existsSync(join(mapDir, `${record.id}.md`))) errors.push(`missing interpretation file ${record.id}.md`)
    for (const m of record.metrics ?? []) {
      if (m.status === 'measured' && !m.baseline) errors.push(`$.metrics[${m.id}]: measured without a baseline`)
      if (m.status === 'gap' && !m.gap && !record.gaps?.length) errors.push(`$.metrics[${m.id}]: gap without a reason`)
      if (m.baseline && m.baseline.p95 !== undefined && m.baseline.samples < 20) errors.push(`$.metrics[${m.id}]: p95 claimed from ${m.baseline.samples} samples`)
    }
    for (const l of record.linked ?? []) if (!existsSync(join(mapDir, `${l.workload}.json`))) errors.push(`$.linked: ${l.workload} has no record`)
    for (const e of errors) problems.push({ file, error: e })
  }
  return problems
}

// ---------------------------------------------------------------- index

export function metricCounts(record) {
  const counts = { gap: 0, 'recipe-only': 0, measured: 0, stale: 0, gated: 0 }
  for (const m of record.metrics ?? []) counts[m.status] = (counts[m.status] ?? 0) + 1
  return counts
}

export function unmeasuredStates(record) {
  const relevant = Object.entries(record.states ?? {}).filter(([, v]) => v.matters).map(([k]) => k)
  const covered = new Set()
  for (const m of record.metrics ?? []) if (['measured', 'gated'].includes(m.status)) for (const st of m.states ?? []) covered.add(st)
  return relevant.filter((k) => !covered.has(k))
}

export function renderIndex(records, gaps, title = 'Performance map') {
  const lines = []
  lines.push(`# ${title}`)
  lines.push('')
  lines.push('Generated by `node scripts/perf-map.mjs index` from the JSON records in this directory. Do not edit by hand; edit the records.')
  lines.push('')
  lines.push('Each workload is a `<id>.json` record (machine-readable, schema in `record.schema.json`) and a `<id>.md` interpretation. Metric status is a state, not a ladder: `gap` names a cost nobody can collect yet, `recipe-only` has a command but no retained receipt, `measured` has a receipt for the current owners, `stale` means an owner changed since the receipt, `gated` means a test asserts it.')
  lines.push('')
  lines.push('| Workload | Lane | Processes | gap | recipe-only | measured | stale | gated | Unmeasured states | Readiness |')
  lines.push('| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | --- | --- |')
  for (const { record } of records) {
    const c = metricCounts(record)
    lines.push(`| [${record.title}](./${record.id}.md) | ${record.lane} | ${record.processes.join(', ')} | ${c.gap} | ${c['recipe-only']} | ${c.measured} | ${c.stale} | ${c.gated} | ${unmeasuredStates(record).join(', ') || '—'} | ${record.readiness ?? ''} |`)
  }
  lines.push('')
  lines.push(`## Accounted gaps (${gaps.gaps.length})`)
  lines.push('')
  lines.push('Census keys no workload measures, each with a reason. Removing a reason moves the key to drift.')
  lines.push('')
  for (const g of gaps.gaps) lines.push(`- \`${g.key}\` — ${g.reason}`)
  lines.push('')
  return lines.join('\n')
}

// ---------------------------------------------------------------- drift

export function drift(censusData, records, gaps) {
  const censusKeys = new Map(censusData.entries.map((e) => [e.key, e]))
  const accounted = new Map()
  for (const { record } of records) for (const a of record.accounts ?? []) accounted.set(a.key, record.id)
  const gapKeys = new Map(gaps.gaps.map((g) => [g.key, g.reason]))
  const matches = (pattern, key) => (pattern.endsWith('*') ? key.startsWith(pattern.slice(0, -1)) : key === pattern)
  const covered = (key) => {
    for (const p of accounted.keys()) if (matches(p, key)) return true
    for (const p of gapKeys.keys()) if (matches(p, key)) return true
    return false
  }
  const unaccounted = []
  for (const e of censusData.entries) if (!covered(e.key)) unaccounted.push(e)
  const dead = []
  const anyCensus = (pattern) => [...censusKeys.keys()].some((k) => matches(pattern, k))
  for (const [key, id] of accounted) if (!anyCensus(key)) dead.push({ key, workload: id })
  for (const [key] of gapKeys) if (!anyCensus(key)) dead.push({ key, workload: 'gaps.json' })
  const blobs = new Map(Object.entries(censusData.files ?? {}))
  for (const e of censusData.entries) if (e.blob && !blobs.has(e.path)) blobs.set(e.path, e.blob)
  const staleOwners = []
  for (const { record } of records) {
    for (const owner of record.owners ?? []) {
      const [path, recorded] = owner.split('@')
      const current = blobs.get(path)
      if (current === undefined) staleOwners.push({ workload: record.id, path, problem: 'not in census' })
      else if (recorded && recorded !== current) staleOwners.push({ workload: record.id, path, problem: `content changed (${recorded.slice(0, 8)} -> ${current.slice(0, 8)})` })
    }
  }
  return { unaccounted, dead, staleOwners, summary: { census: censusData.entries.length, accounted: accounted.size, gaps: gapKeys.size, unaccounted: unaccounted.length, dead: dead.length, staleOwners: staleOwners.length } }
}

// ---------------------------------------------------------------- check

export function aggregate(samples, how) {
  const xs = (samples ?? []).filter((x) => typeof x === 'number' && Number.isFinite(x))
  if (xs.length === 0) return { value: null, n: 0, discarded: (samples ?? []).length }
  const sorted = [...xs].sort((a, b) => a - b)
  const q = (p) => sorted[Math.min(sorted.length - 1, Math.ceil(p * sorted.length) - 1)]
  let value
  switch (how) {
    case 'p95': value = q(0.95); break
    case 'p99': value = q(0.99); break
    case 'max': value = sorted[sorted.length - 1]; break
    case 'sum': value = xs.reduce((a, b) => a + b, 0); break
    case 'mean': value = xs.reduce((a, b) => a + b, 0) / xs.length; break
    case 'last': value = xs[xs.length - 1]; break
    case 'raw': value = xs; break
    case 'slope': value = null; break
    default: value = sorted.length % 2 ? sorted[(sorted.length - 1) / 2] : (sorted[sorted.length / 2 - 1] + sorted[sorted.length / 2]) / 2
  }
  return { value, n: xs.length, discarded: (samples ?? []).length - xs.length }
}

function compare(value, comparator, limit) {
  switch (comparator) {
    case '<': return value < limit
    case '>=': return value >= limit
    case '>': return value > limit
    default: return value <= limit
  }
}

function direction(metric) {
  if (metric.betterWhen === 'lower' || metric.betterWhen === 'higher') return metric.betterWhen
  const c = metric.budget?.comparator
  if (c === '<=' || c === '<') return 'lower'
  if (c === '>=' || c === '>') return 'higher'
  return null
}

const VERDICT_ORDER = ['fail', 'regression', 'inconclusive', 'not-comparable', 'advisory-exceeded']
const worst = (verdicts) => VERDICT_ORDER.find((v) => verdicts.includes(v)) ?? 'pass'

export function checkResult(record, result, receipt, tolerance = 0.1) {
  const metric = (record.metrics ?? []).find((m) => m.id === result.metric)
  if (!metric) return { workload: record.id, metric: result.metric, verdict: 'fail', findings: ['metric not in record'] }
  const how = metric.aggregation ?? 'median'
  const agg = aggregate(result.samples, how)
  const timing = ['ms', 'us', 's', 'fps'].includes(metric.unit)
  const out = { workload: record.id, metric: metric.id, unit: metric.unit, kind: metric.kind, aggregation: how, samples: agg.n, discardedSamples: agg.discarded, aggregate: agg.value, findings: [] }
  const verdicts = []
  const scalar = typeof agg.value === 'number'
  if (agg.discarded > 0) out.findings.push(`${agg.discarded} non-numeric sample(s) discarded`)
  if (how === 'slope') verdicts.push('inconclusive'), out.findings.push('slope needs a time axis; not supported by check')
  else if (how === 'raw') verdicts.push('inconclusive'), out.findings.push('raw aggregation: samples retained, nothing judged')
  else if (agg.n === 0) verdicts.push('inconclusive'), out.findings.push('no numeric samples')
  else if (timing && agg.n < 3) verdicts.push('inconclusive'), out.findings.push(`${agg.n} timing samples cannot support a verdict`)
  else if (['p95', 'p99'].includes(how) && agg.n < 20) verdicts.push('inconclusive'), out.findings.push(`${how} claimed from ${agg.n} samples`)
  if (metric.invariant) {
    if (result.invariantHolds === false) verdicts.push('fail'), out.findings.push(`invariant violated: ${metric.invariant}`)
    else if (result.invariantHolds !== true) verdicts.push('inconclusive'), out.findings.push(`invariant not evaluated by the receipt: ${metric.invariant}`)
  }
  if (metric.budget && scalar) {
    const b = metric.budget
    const comparator = b.comparator ?? '<='
    const ok = compare(agg.value, comparator, b.value)
    out.budget = { value: b.value, unit: b.unit, comparator, status: b.status, ok }
    if (!ok) {
      if (b.status === 'ruled') verdicts.push('fail'), out.findings.push(`ruled budget ${comparator} ${b.value} ${b.unit} exceeded: ${agg.value}`)
      else verdicts.push('advisory-exceeded'), out.findings.push(`${b.status} budget ${comparator} ${b.value} ${b.unit} exceeded: ${agg.value}`)
    }
  }
  const base = metric.baseline
  if (base && scalar) {
    const dir = direction(metric)
    const baseValue = base.aggregation === how && typeof base.aggregate === 'number' ? base.aggregate : how === 'median' && typeof base.median === 'number' ? base.median : null
    if (!receipt.seriesId || receipt.seriesId !== base.seriesId) {
      out.baseline = { seriesId: base.seriesId, comparable: false }
      verdicts.push('not-comparable'), out.findings.push(`receipt series ${receipt.seriesId ?? '(none)'} differs from baseline series ${base.seriesId}`)
    } else if (baseValue === null) {
      out.baseline = { seriesId: base.seriesId, comparable: false }
      verdicts.push('not-comparable'), out.findings.push(`baseline has no ${how} aggregate to compare against`)
    } else if (!dir) {
      out.baseline = { seriesId: base.seriesId, comparable: false }
      verdicts.push('not-comparable'), out.findings.push('record does not say whether lower or higher is better (betterWhen or a budget comparator)')
    } else {
      const delta = agg.value - baseValue
      const relative = baseValue === 0 ? null : delta / Math.abs(baseValue)
      const worse = baseValue === 0 ? (dir === 'lower' ? delta > 0 : false) : dir === 'lower' ? relative > tolerance : relative < -tolerance
      out.baseline = { seriesId: base.seriesId, comparable: true, aggregate: baseValue, delta, relative, tolerance, betterWhen: dir, worse }
      if (worse) verdicts.push('regression'), out.findings.push(baseValue === 0 ? `baseline was 0, now ${agg.value}` : `${(relative * 100).toFixed(1)} % ${dir === 'lower' ? 'higher' : 'lower'} than baseline ${baseValue} (tolerance ${tolerance * 100} %)`)
    }
  }
  if (metric.kind === 'lower-bound' && out.findings.length === 0) out.findings.push('sampled lower bound: a small improvement is not demonstrable; large changes under an identical policy are')
  out.verdict = worst(verdicts)
  return out
}

export function checkReceipt(receipt, records, tolerance) {
  const entry = records.find(({ record }) => record.id === receipt.workload)
  if (!entry) return { verdict: 'fail', results: [], findings: [`no record for workload ${receipt.workload}`] }
  const list = receipt.results ?? (receipt.metric ? [{ metric: receipt.metric, samples: receipt.samples, invariantHolds: receipt.invariantHolds }] : [])
  if (list.length === 0) return { workload: receipt.workload, seriesId: receipt.seriesId ?? null, verdict: 'inconclusive', results: [], findings: ['receipt carries no results'] }
  const results = list.map((r) => checkResult(entry.record, r, receipt, tolerance))
  return { workload: receipt.workload, seriesId: receipt.seriesId ?? null, verdict: worst(results.map((r) => r.verdict)), results }
}

// ---------------------------------------------------------------- cli

function arg(name) {
  const i = process.argv.indexOf(name)
  return i === -1 ? undefined : process.argv[i + 1]
}

function main() {
  const cmd = process.argv[2]
  if (cmd === 'census') {
    const data = census()
    const out = arg('--out')
    const text = JSON.stringify(data, null, 2) + '\n'
    if (out) { writeFileSync(out, text); console.log(JSON.stringify({ wrote: out, head: data.head, fileCount: data.fileCount, counts: data.counts })) }
    else process.stdout.write(text)
    return
  }
  if (cmd === 'validate') {
    const problems = validateRecords()
    for (const p of problems) console.error(`${p.file}: ${p.error}`)
    console.log(JSON.stringify({ records: loadRecords().length, problems: problems.length }))
    process.exitCode = problems.length ? 1 : 0
    return
  }
  if (cmd === 'index') {
    const problems = validateRecords()
    if (problems.length) { for (const p of problems) console.error(`${p.file}: ${p.error}`); process.exitCode = 1; return }
    writeFileSync(join(MAP_DIR, 'README.md'), renderIndex(loadRecords(), loadGaps()))
    console.log(JSON.stringify({ wrote: join(MAP_DIR, 'README.md') }))
    return
  }
  if (cmd === 'drift') {
    const file = arg('--census')
    const data = file ? JSON.parse(readFileSync(file, 'utf8')) : census()
    const report = drift(data, loadRecords(), loadGaps())
    process.stdout.write(JSON.stringify(report, null, 2) + '\n')
    process.exitCode = report.unaccounted.length || report.dead.length || report.staleOwners.length ? 1 : 0
    return
  }
  if (cmd === 'check') {
    const file = process.argv[3]
    if (!file || file.startsWith('--')) { console.error('usage: perf-map.mjs check <receipt.json> [--tolerance 0.1]'); process.exitCode = 2; return }
    const tolerance = arg('--tolerance') ? Number(arg('--tolerance')) : 0.1
    const report = checkReceipt(JSON.parse(readFileSync(file, 'utf8')), loadRecords(), tolerance)
    process.stdout.write(JSON.stringify(report, null, 2) + '\n')
    process.exitCode = ['fail', 'regression'].includes(report.verdict) ? 1 : 0
    return
  }
  console.error('usage: perf-map.mjs census [--out f] | validate | index | drift [--census f] | check <receipt.json> [--tolerance t]')
  process.exitCode = 2
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main()
